let promise = new Promise((resolve, reject) => {
    reject("Error occurred");
});
console.log(promise);